app = "employee-management-system-vbqpcwle"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8001"
  PYTHONPATH = "/app"
  DATABASE_URL = "postgres://user_lcdajasdhr:sOmqrAFn9q4N6msOvAb4@devinapps-backend-prod.cluster-clussqewa0rh.us-west-2.rds.amazonaws.com/db_bkfgnsyihz?sslmode=require"
  SECRET_KEY = "fahimimran0088@gmail.com"
  API_V1_STR = "/api/v1"
  PROJECT_NAME = "Employee Management System"
  VERSION = "1.0.0"
  ACCESS_TOKEN_EXPIRE_MINUTES = "30"
  BACKEND_CORS_ORIGINS = '["https://employee-management-system.netlify.app", "http://localhost:5173"]'

[[services]]
  internal_port = 8001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
