[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "8001"
API_V1_STR = "/api/v1"
PROJECT_NAME = "Employee Management System"
VERSION = "1.0.0"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
ENVIRONMENT = "production"
