version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://user_lcdajasdhr:sOmqrAFn9q4N6msOvAb4@devinapps-backend-prod.cluster-clussqewa0rh.us-west-2.rds.amazonaws.com/db_bkfgnsyihz?sslmode=require
      - SECRET_KEY=${fahim123}
      - CORS_ORIGINS=https://remarkable-dieffenbachia-df2ca5.netlify.app,http://localhost:3000
      - API_V1_STR=/api/v1
      - PROJECT_NAME=Employee Management System
      - VERSION=1.0.0
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=production
      - PORT=8001
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
