name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Production
        env:
          DATABASE_URL: postgresql://user_lcdajasdhr:sOmqrAFn9q4N6msOvAb4@devinapps-backend-prod.cluster-clussqewa0rh.us-west-2.rds.amazonaws.com/db_bkfgnsyihz?sslmode=require
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CORS_ORIGINS: https://remarkable-dieffenbachia-df2ca5.netlify.app,https://employee-management-system-nauue8lh.devinapps.com
        run: |
          docker pull ghcr.io/${{ github.repository }}/backend:latest
          docker stop ems-backend || true
          docker rm ems-backend || true
          docker run -d \
            --name ems-backend \
            -p 8002:8001 \
            -e DATABASE_URL="$DATABASE_URL" \
            -e SECRET_KEY="$SECRET_KEY" \
            -e CORS_ORIGINS="$CORS_ORIGINS" \
            -e API_V1_STR="/api/v1" \
            -e PROJECT_NAME="Employee Management System" \
            -e VERSION="1.0.0" \
            -e ACCESS_TOKEN_EXPIRE_MINUTES="30" \
            -e ENVIRONMENT="production" \
            ghcr.io/${{ github.repository }}/backend:latest
